version: 0.1.0   

name: A GitHub stack to deploy an Express(Node.js) website to Azure App service
description: A GitHub Stack to develop, preview, and deploy an Express(Node.js) website to Azure App service in seconds.

branding:
  icon: 'cloud'
  color: 'red'

inputs:

  - name: AZURE_APP_NAME
    description: Enter the name of the Azure App Service
    is-secret: false
    required: true
    
  - name: AZURE_WEBAPP_PUBLISH_PROFILE
    description: Enter the Azure App Service Publish profile
    is-secret: true
    required: true

configs:
   repo-metadata:
      parameters:
        description: 'A Nodejs website deployed in Azure App Service'
        secrets: 
          - name: AZURE_WEBAPP_PUBLISH_PROFILE
            value: ${{inputs.AZURE_WEBAPP_PUBLISH_PROFILE}}
        topics:
        - nodejs
        - expressjs
        - azure
        
   environments:                                        
    - name: development
      parameters: 
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*

init:
 uses: "stack-init.yaml"
