version: 0.1.0   

name: A stack to deploy nodejs app to Azure
description: A stack to deploy nodejs app to Azure

branding:
  icon: 'azure.svg'
  color: 'blue'

inputs:

  - name: AZURE_APP_NAME
    description: Enter the name of the Azure App which has been configured to host the website
    is_secret: true
    required: true
    
  - name: AZURE_WEBAPP_PUBLISH_PROFILE
    description: Enter the Azure Publish profile. 
    is_secret: true
    required: true
  
configs:
  - repo-metadata:
      parameters:
        description: 'A Nodejs website deployed in Azure App Service'
        secrets: 
          - name: AZURE_APP_NAME
            value: ${{inputs.AZURE_APP_NAME}}
          - name: AZURE_WEBAPP_PUBLISH_PROFILE
            value: ${{inputs.AZURE_WEBAPP_PUBLISH_PROFILE}}
        topics:
        - nodejs
        - expressjs
        - azure

  - branches:   
    - name: main
      parameters:
        dismiss-stale-reviews: true                      
        required-approving-review-count: 0
        require-code-owner-reviews: false

  - environments:                                        
    - name: production
      parameters:
        protected-branches: false

init:
- uses: ".github/workflows/stack-init.yaml"
